name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    # L'option `pull_request` est également utile si vous voulez que le workflow soit déclenché par un PR vers `main`
    # pull_request:
    #   branches:
    #     - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2
    
    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Cache Docker layers to speed up subsequent builds
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker-compose -f docker-compose.yml build api

    # Tag the image
    - name: Tag Docker image
      run: |
        IMAGE_NAME="your-dockerhub-username/your-image-name"
        docker tag your-image-name:latest $IMAGE_NAME:latest

    # Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/your-image-name:latest


