name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    
    steps:
    # Récupérer le code depuis le dépôt
    - name: Checkout repository
      uses: actions/checkout@v2
    
    # Se connecter à Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.romain99 }}
        password: ${{ secrets.dckr_pat_dO908U8pElNTVz-ucAp8OD2UUA4 }}

    # Configurer Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Cacher les couches Docker pour accélérer les builds suivants
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    # Construire l'image Docker
    - name: Build Docker image
      run: |
        docker-compose -f docker-compose.yml build api

    # Taguer l'image
    - name: Tag Docker image
      run: |
        docker tag app-api:latest exo4dockercomposemongodb/api-app:latest

    # Pousser l'image Docker sur Docker Hub
    - name: Push Docker image
      run: |
        docker push exo4dockercomposemongodb/api-app:latest


    # Push the Docker image to Docker Hub
    - name: Push Docker image
      run: |
        docker push exo4dockercomposemongodb/api-app:latest
